title: UGA Terry FinTech CI/CD Class with Github
description: This site demonstrates the Git and GitHub can be used to kick off a CI/CD pipeline to update a class roster in real-time.
baseurl: "/UGA-Terry-FinTech-Git-Class.github.io"
url: "https://uga-terry-fintech-class-fall-2025.github.io"

# Jekyll "collection" for students
collections:
  students:
    output: true
    permalink: /_students/:name/

# Default layout for all student pages
defaults:
  - scope:
      path: ""
      type: "students"
    values:
      layout: student
